<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new Listing';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('listing', array('action' => 'add')));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('product_code'));
 echo $this->formRow($form->get('item_sku'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();