<?php
 $title = 'My Listing';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('listing', array('action'=>'add'));?>">Add new Listing</a>
 </p>

 <table class="table">
 <tr>
     <th>Product Code</th>
     <th>Item Sku</th>
     <th>Item name</th>
 </tr>
 <?php foreach ($listings as $listing) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($listing->product_code);?></td>
     <td><?php echo $this->escapeHtml($listing->item_sku);?></td>
     <td>
         <a href="<?php echo $this->url('listing',
             array('action'=>'edit', 'id' => $listing->id));?>">Edit</a>
         <a href="<?php echo $this->url('listing',
             array('action'=>'delete', 'id' => $listing->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>